package fake_model

import "github.com/daarlabs/farah/model/select_model"

var (
	Categories = []select_model.Option[int]{
		{Value: 1, Text: "Operating System"},
		{Value: 2, Text: "Database Systems"},
		{Value: 3, Text: "Productivity Software"},
		{Value: 4, Text: "Business Intelligence"},
		{Value: 5, Text: "Cloud Services"},
		{Value: 6, Text: "Collaboration Tools"},
		{Value: 7, Text: "Data Analytics"},
		{Value: 8, Text: "Enterprise Solutions"},
		{Value: 9, Text: "CRM Software"},
		{Value: 10, Text: "ERP Systems"},
		{Value: 11, Text: "Network Management"},
		{Value: 12, Text: "Security Software"},
		{Value: 13, Text: "Virtualization"},
		{Value: 14, Text: "AI & Machine Learning"},
		{Value: 15, Text: "Development Tools"},
		{Value: 16, Text: "Web Hosting"},
		{Value: 17, Text: "E-commerce Systems"},
		{Value: 18, Text: "Mobile Applications"},
		{Value: 19, Text: "Game Development"},
		{Value: 20, Text: "Graphic Design Software"},
		{Value: 21, Text: "Video Production"},
		{Value: 22, Text: "Educational Software"},
		{Value: 23, Text: "IoT Solutions"},
		{Value: 24, Text: "Blockchain Solutions"},
		{Value: 25, Text: "Cybersecurity Solutions"},
		{Value: 26, Text: "Compliance Software"},
		{Value: 27, Text: "Healthcare Systems"},
		{Value: 28, Text: "Legal Technology"},
		{Value: 29, Text: "Real Estate Software"},
		{Value: 30, Text: "Marketing Tools"},
		{Value: 31, Text: "Sales Enablement Tools"},
		{Value: 32, Text: "Human Resources Systems"},
		{Value: 33, Text: "Project Management Tools"},
		{Value: 34, Text: "Customer Support Platforms"},
		{Value: 35, Text: "Payment Processing Systems"},
		{Value: 36, Text: "Supply Chain Management"},
		{Value: 37, Text: "Transportation Management Systems"},
		{Value: 38, Text: "Energy Management Systems"},
		{Value: 39, Text: "Public Sector Solutions"},
		{Value: 40, Text: "Nonprofit Software"},
	}
)
